stages:
  - appium


appium_job:
  stage: appium
  tags:
    - android-host-1
  before_script:
    - export ANDROID_HOME=$HOME/Android/Sdk
    - export ANDROID_SDK_ROOT=$HOME/Android/Sdk
    - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  script:
    - appium --address 0.0.0.0 --port 4723 &
  after_script:
    - python3 telegram_bot/client.py -n appium_job
  retry: 2
