stages:
  - build


build_job:
  stage: build
  tags:
    - android-host-1
  before_script:
    - echo y ; echo y ; echo y ; echo y ; echo y ; echo y | /home/npermyakov/Android/Sdk/tools/bin/sdkmanager --licenses
  script:
    - echo $ANDROID_HOST_PASSWORD | sudo -S sysctl -w dev.i915.perf_stream_paranoid=0
    - DISPLAY=:0 xterm -e '/home/npermyakov/Android/Sdk/emulator/emulator -avd Pixel_3a_XL_API_30 -no-snapshot-load -memory 3072'
  after_script:
    - python3 telegram_bot/client.py -n build_job
