stages:
  - build


build_job:
  stage: build
  tags:
    - android-host-1
  script:
    - |
      docker run \
      -e ADBKEY="$(cat ~/.android/adbkey)" \
      --device /dev/kvm \
      --publish 8554:8554/tcp \
      --publish 5555:5555/tcp  \
      us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2
  after_script:
    - python3 telegram_bot/client.py -n build_job
