stages:
  - build


build_job:
  stage: build
  tags:
    - android-host-1
  before_script:
    - echo y ; echo y ; echo y ; echo y ; echo y ; echo y | /home/npermyakov/Android/Sdk/tools/bin/sdkmanager --licenses
  script:
    - DISPLAY=:0 xterm -e '/home/npermyakov/Android/Sdk/emulator/emulator -avd Pixel_3a_API_30'
  after_script:
    - python3 telegram_bot/client.py -n build_job
