stages:
  - build_proxy


build_proxy_job:
  stage: build_proxy
  tags:
    - android-host-1
  before_script:
    - echo $ANDROID_HOST_PASSWORD | chmod 777 ./xterm_emulator.log
    - echo $ANDROID_HOST_PASSWORD | sudo -S echo -e "\n################# NEW RECARD @@@@@@@@@@@@@@@\n" >> ./xterm_emulator.log
  script:
    - DISPLAY=:0 xterm -e '/home/npermyakov/Android/Sdk/emulator/emulator -avd Pixel_3a_XL_API_30 -no-snapshot-load -gpu guest -memory 3072 -http-proxy http:10.60.21.50//:8080 2>&1 | tee -a ./xterm_emulator.log'
  after_script:
    - python3 telegram_bot/client.py -n build_proxy_job
  artifacts:
    when: always
    paths:
      - ./xterm_emulator.log
    expire_in: 3 days