stages:
  - build_proxy


build_proxy_job:
  stage: build_proxy
  tags:
    - android-host-1
  script:
    - DISPLAY=:0 xterm -e '/home/npermyakov/Android/Sdk/emulator/emulator -avd Pixel_3a_XL_API_30 -no-snapshot-load -gpu guest -memory 3072 -http-proxy http:10.60.21.50//:8080'
  after_script:
    - python3 telegram_bot/client.py -n build_proxy_job
