stages:
  - postgres
  - grafana


postgres_job:
  stage: postgres
  tags:
    - android-host-1
  before_script:
    - docker-compose -f ./db/docker-compose.yml up -d || true
  script:
    - docker exec postgres_container bash -c 'psql -h localhost -U n.permyakov postgres -f create_database.sql'
    - docker exec postgres_container bash -c 'psql -h localhost -U n.permyakov metric_autotests -f create_tables.sql'
  after_script:
    - python3 telegram_bot/client.py -n postgres_job

grafana_job:
  stage: grafana
  tags:
    - android-host-1
  script:
    - python3 db/autorecovery.py
  after_script:
    - python3 telegram_bot/client.py -n grafana_job