from selenium.webdriver.common.by import By


class MoviesPageLocators:
    feature_app_bar = (By.ID, 'ru.rambler.kassa.beta:id/featuringAppBar')
    tabs_rv = (By.ID, 'ru.rambler.kassa.beta:id/tabsRv')
    bottom_menu_id = (By.ID, 'ru.rambler.kassa.beta:id/bottomNavigation')
    event_name = (By.ID, 'ru.rambler.kassa.beta:id/eventName')
    back_button = (By.ID, 'ru.rambler.kassa.beta:id/leftIcon')
    tabs_events_id = (By.ID, 'ru.rambler.kassa.beta:id/tabsRv')
    carousel_rv = (By.ID, 'ru.rambler.kassa.beta:id/carouselRv')
    list_session_view = (By.ID, 'ru.rambler.kassa.beta:id/listSessionView')
    fastbuy_ticket_id = (By.ID, 'ru.rambler.kassa.beta:id/buyTicket')
    nearest_place_distance = (By.ID, 'ru.rambler.kassa.beta:id/placeDistanceTv')
    place_label = (By.ID, 'ru.rambler.kassa.beta:id/placeLabel')
    nearest_place = (By.ID, 'ru.rambler.kassa.beta:id/nearestPlaceName')
    arrow_right = (By.ID, 'ru.rambler.kassa.beta:id/forward')
    session_date = (By.ID, 'ru.rambler.kassa.beta:id/sessionDate')
    session_tags = (By.ID, 'ru.rambler.kassa.beta:id/sessionTags')
    session_price = (By.ID, 'ru.rambler.kassa.beta:id/sessionPrice')
    movies_title = (By.ID, 'ru.rambler.kassa.beta:id/title')
    event_img = (By.ID, 'ru.rambler.kassa.beta:id/eventImg')
    compilation_img = (By.ID, 'ru.rambler.kassa.beta:id/compilationImg')
    mature_text = (By.ID, 'ru.rambler.kassa.beta:id/matureText')
    premier_date = (By.ID, 'ru.rambler.kassa.beta:id/premiereDate')
    favorite_container = (By.ID, 'ru.rambler.kassa.beta:id/favoriteBtnContainer')
    filters_carousel = (By.ID, 'ru.rambler.kassa.beta:id/filtersRv')
    event_title = (By.ID, 'ru.rambler.kassa.beta:id/eventTitle')
    right_btn = (By.ID, 'ru.rambler.kassa.beta:id/rightBtn')
    title_tv = (By.ID, 'ru.rambler.kassa.beta:id/titleTv')