version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-n.permyakov}
      POSTGRES_PASSWORD: $ANDROID_HOST_PASSWORD
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./create_database.sql:/create_database.sql
       - ./create_tables.sql:/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  grafana:
    container_name: grafana_container
    image: grafana/grafana:7.5.7
    environment:
      GF_USERS_DEFAULT_THEME: "light"
      GF_SECURITY_ADMIN_USER: ${ADMIN_USER:-n.permyakov}
      GF_SECURITY_ADMIN_PASSWORD: $ANDROID_HOST_PASSWORD
    ports:
      - "3000:3000"
    links:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-n.permyakov@rambler-co.ru}
      PGADMIN_DEFAULT_PASSWORD: $ANDROID_HOST_PASSWORD
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    links:
      - postgres
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: